controller_list:
  - name: EffortJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

    gains: #copied from Erdal's Blog
      panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
      panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
      panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
      panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
      panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
      panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
      panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

  - name: EffortJointInterface_trajectory_gripper
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - panda_finger_joint1
      - panda_finger_joint2
    gains:
      panda_finger_joint1: {p: 30,  d: 1, i: 0, i_clamp: 0} 
      panda_finger_joint2: {p: 30,  d: 1, i: 0, i_clamp: 0}

      
