controller_list:
  - name: position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

  - name: PositionJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7


  - name: EffortJointInterface_trajectory_gripper
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - panda_finger_joint1
      - panda_finger_joint2
    gains:
      panda_finger_joint1: {p: 30,  d: 1, i: 0, i_clamp: 0} 
      panda_finger_joint2: {p: 30,  d: 1, i: 0, i_clamp: 0}
