#panda:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
    joints: 
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7 
      - panda_finger_joint1
      - panda_finger_joint2
    
  # Forward Position Controllers --------------------------------------- 
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

    constraints:
      goal_time: 0.6                   # was 0.6 - changed to 2.0 (Erdal)
      panda_joint1: 
        goal: 0.1 # was 0.1  ...
        trajectory: 0.1
      panda_joint2: 
        goal: 0.1
        trajectory: 0.1
      panda_joint3: 
        goal: 0.1
        trajectory: 0.1
      panda_joint4: 
        goal: 0.1
        trajectory: 0.1
      panda_joint5: 
        goal: 0.1
        trajectory: 0.1
      panda_joint6: 
        goal: 0.1
        trajectory: 0.1
      panda_joint7: 
        goal: 0.1
        trajectory: 0.1

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

    
  EffortJointInterface_trajectory_gripper:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - panda_finger_joint1
      - panda_finger_joint2

    gains:
      panda_finger_joint1: {p: 30,  d: 1, i: 0, i_clamp: 0}
      panda_finger_joint2: {p: 40,  d: 1, i: 0, i_clamp: 0}

    constraints:
      goal_time: 1.5                   # Override default
      panda_finger_joint1: 
         goal: 0.01 #should be 0.0001 (@ real panda)...
      panda_finger_joint2:
         goal: 0.01

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

